---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: system-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.127.0.0.1.nip.io"
