---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus
spec:
  hosts:
  - prometheus.127.0.0.1.nip.io
  gateways:
  - system-gateway
  http:
  - name: "default"
    route:
    - destination:
        host: prometheus.istio-system.svc.cluster.local
        port:
          number: 9090
