---
apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  type: NodePort
  selector:
    app: envoy
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: envoy
  name: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - image: envoyproxy/envoy:v1.21.2
        args:
        - -c
        - /etc/envoy.yaml
        name: envoy
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/envoy.yaml
          subPath: envoy.yaml
      volumes:
      - name: config
        configMap:
          name: envoy-config

