kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # Istio HTTP
  - containerPort: 30080
    hostPort: 80
  # Istio HTTPS
  - containerPort: 30443
    hostPort: 443
  # Istio status port
  - containerPort: 31521
    hostPort: 31521
- role: worker
- role: worker
- role: worker
